### ISSUE TITLE
GPIO with delay issue.

### ISSUE THREAD

**Issue by schef** [elcritch/nesper#8]
Hi, thanks for the awesome lib. I am using it with LilyGO T-Beam.
I am successfully using uart with GPS and I am very excited about it. While i was trying to setup the I2C i wanted to test if i am using the right pins. So I used the GPIO configure with delayMillis. While i was mixing this two lines the fw freezes. This happens on pins 21 and 22 (I2C pins) but not on 23. Do you have any idea?

```nim
  proc printf*(formatstr: cstring) {.importc: "printf", varargs, header: "stdio.h".}

  printf("output\n")
  {GPIO_NUM_23}.configure(MODE_OUTPUT)
  delay(Millis(100))
  printf("false\n")
  GPIO_NUM_23.setLevel(false) 
  delay(Millis(100))
  printf("true\n")
  GPIO_NUM_23.setLevel(true)
  delay(Millis(100))
  printf("false\n")
  GPIO_NUM_23.setLevel(false)

  printf("output\n")
  {GPIO_NUM_21}.configure(MODE_OUTPUT)
  delay(Millis(100))
  printf("false\n")
  GPIO_NUM_21.setLevel(false) 
  delay(Millis(100))
  printf("true\n")
  GPIO_NUM_21.setLevel(true)
  #CRASH
  delayMillis(100)
  printf("false\n")
  GPIO_NUM_21.setLevel(false) 
```

**Comment by elcritch** [comment]
Thanks! Are you using / configuring GPIO 21/22 as I2C pins before trying to toggle them? 

What I suspect might be happening is a deadlock in FreeRTOS / ESP-IDF. For example if GPIO21 has already been configured for I2C then the ESP-IDF gpio drivers might not be able to get a lock for the gpio pin and it'll hang. I've had that happen before but usually by mixing up SPI buses. 

Also it'd be good to know if it's just freezing or if it's crashing and printing a stack trace. It sounds like it's just hanging and never finishes that code? 

Here's the [setLevel proc](https://github.com/elcritch/nesper/blob/9dc8f63f92ae9b975e41cc33e5cf1d1e6c127d80/src/nesper/gpios.nim#L38) which really doesn't do anything too complicated and should raise an exception if the ESP-IDF function doesn't return ESP_OK. 

P.S. checking the [pin reference](https://randomnerdtutorials.com/esp32-pinout-reference-gpios/) doesn't yield anything like the pins being input only.

**Comment by schef** [comment]
Thanks for your response. In the end I did not find why this was happening but what is important is that I2C works. :)
